
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'APPLICATION ASSIGMENT BACK BEGIN BOOL COMMA CONTINUE DO DOUBLE_QUOTE DRILL ELSE END EQ FALSE FORWARD FRONT FUNCTION_OF GREATER IF INTEGER INT_DEX LBRACKET LEFT LESS LMS L_QBRACKET MINUS NEWLINE NOTEQ OF PLUS POP PUSH QUOTE RBRACKET REFLECT RETURN RIGHT ROTATE_LEFT ROTATE_RIGHT R_QBRACKET SPACE STRING THEN TO TRUE UNDEFINED UNTIL VARIABLE VECTORprogram : stmt_liststmt_list : VARIABLE NEWLINE'
    
_lr_action_items = {'VARIABLE':([0,],[3,]),'$end':([1,2,4,],[0,-1,-2,]),'NEWLINE':([3,],[4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'stmt_list':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> stmt_list','program',1,'p_program','parser.py',33),
  ('stmt_list -> VARIABLE NEWLINE','stmt_list',2,'p_stmt_list','parser.py',37),
]
